2018-04-18 18:06:57.146 +02:00 [Error] Fatal Error: http://5by5.tv/people/john-siracusa/rss, "System.IO.IOException: The file '/home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting.Cli/cache/Error_E74B341FAF5F2A193F97FF5E58F2F8AA' already exists.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Ultraschall.Podcasting.Caching.FileCache.<SetAsync>d__10.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/Caching/FileCache.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ultraschall.Podcasting.PodcastFeedService.<>c__DisplayClass9_1.<<UpdateCache>b__0>d.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/PodcastFeedService.cs:line 174"
2018-04-18 18:06:57.606 +02:00 [Error] Fatal Error: http://aerostat.rpod.ru/rss.xml, "System.IO.IOException: The file '/home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting.Cli/cache/Error_C65958CD61DE365FF5DFEE93E265158E' already exists.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Ultraschall.Podcasting.Caching.FileCache.<SetAsync>d__10.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/Caching/FileCache.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ultraschall.Podcasting.PodcastFeedService.<>c__DisplayClass9_1.<<UpdateCache>b__0>d.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/PodcastFeedService.cs:line 174"
2018-04-18 18:06:57.619 +02:00 [Error] Fatal Error: http://aerostat.rpod.ru/rss.xml, "System.IO.IOException: The file '/home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting.Cli/cache/Error_C65958CD61DE365FF5DFEE93E265158E' already exists.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Ultraschall.Podcasting.Caching.FileCache.<SetAsync>d__10.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/Caching/FileCache.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ultraschall.Podcasting.PodcastFeedService.<>c__DisplayClass9_1.<<UpdateCache>b__0>d.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/PodcastFeedService.cs:line 174"
2018-04-18 18:06:57.935 +02:00 [Error] Fatal Error: http://alternativlos.org/alternativlos.rss, "System.IO.IOException: The file '/home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting.Cli/cache/Error_C567A934D59AE819377721C82AA18456' already exists.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Ultraschall.Podcasting.Caching.FileCache.<SetAsync>d__10.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/Caching/FileCache.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ultraschall.Podcasting.PodcastFeedService.<>c__DisplayClass9_1.<<UpdateCache>b__0>d.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/PodcastFeedService.cs:line 174"
2018-04-18 18:06:57.941 +02:00 [Error] Fatal Error: http://alternativlos.org/alternativlos.rss, "System.IO.IOException: The file '/home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting.Cli/cache/Error_C567A934D59AE819377721C82AA18456' already exists.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Ultraschall.Podcasting.Caching.FileCache.<SetAsync>d__10.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/Caching/FileCache.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ultraschall.Podcasting.PodcastFeedService.<>c__DisplayClass9_1.<<UpdateCache>b__0>d.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/PodcastFeedService.cs:line 174"
2018-04-18 18:06:58.232 +02:00 [Error] Fatal Error: http://anyca.st/feed/mp3, "System.IO.IOException: The file '/home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting.Cli/cache/Error_CA88114A3F7E878DBA5B0FC82063FA76' already exists.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Ultraschall.Podcasting.Caching.FileCache.<SetAsync>d__10.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/Caching/FileCache.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ultraschall.Podcasting.PodcastFeedService.<>c__DisplayClass9_1.<<UpdateCache>b__0>d.MoveNext() in /home/danlin/Projects/ultraschall-playground/danlin/Ultraschall.Podcasting/PodcastFeedService.cs:line 174"
